### PR TITLE
Automatic Android manifest permissions for OpenXR

### PR DESCRIPTION
**Pull request by rblenkinsopp**
## Summary

Adds automatic Android manifest modifications for OpenXR:

- Adds the OpenXR runtime service intent queries statements (as Unity doesn't currently do this).
- Adds Ultraleap Tracking Service/API layer package queries statement to work around Android 11 package visibility changes.
- Adds Meta hand-tracking features permissions.
- Adds support for requesting Meta high-frequency hand-tracking.

## Contributor Tasks

- [x] Pair review with a member of the QA team.
- [ ] Add any release testing considerations to the MR for the next release.
- [x] Consider any licensing/other legal implications for this MR e.g. notices required by any new libraries.
- [x] If this MR closes a Jira issue, make sure the fix version on the JIRA issue is set to the correct one.

## Reviewer Tasks

[Use emojis in review threads to communicate intent and help contributors.](https://github.com/ultraleap/UnityPlugin/blob/develop/CONTRIBUTING.md#review-threads)

- [x] Code reviewed.
- [x] Non-code assets e.g. Unity assets/scenes reviewed.
- [ ] Checked and agree with release testing considerations added to MR for the next release.
- [x] Check that the `<queries><package android:name="org.khronos.openxr.OpenXRRuntimeService" /></queries>` is added to the manifest when building for Android SDK version 30 or higher.
- [x] Check that the "Meta Permissions" option adds `<uses-feature android:name="oculus.software.handtracking" android:required="false" />` and `<uses-permission android:name="com.oculus.permission.HAND_TRACKING" />` to the AndroidManifest.xml, and does not when not selected.
- [x] Check that the "Meta High-Frequency" option adds `<meta-data android:name="com.oculus.handtracking.frequency" android:value="HIGH" />` to the `<application>` element of the manifest and not when not selected.

The generated AndroidManifest.xml can be inspected by loading the Unity built APK into AndroidStudio, or using a command-line look like `apktool`.

## Closes JIRA Issue

Closes UNITY-509 (Quest/Meta hand-tracking support over OpenXR)
Works around OXR-190 (Windows 11 package visibility changes)

### CODE REVIEW

**Comment by MattGrayUL** [comment]
@rblenkinsopp FYI this PR now has some changelog conflicts

**Comment by rblenkinsopp** [comment]
> @rblenkinsopp FYI this PR now has some changelog conflicts

I've rebased now and adjusted the changelog accordingly

**Review by MattGrayUL — APPROVED** [review]
Checked the code and tested locally, works as expected and adds the correct elements to the androidmanifest

I don't know if this requires any additional checks from QA but is worth asking before hitting merge, otherwise I approve :)

**Comment by Greg-UL** [comment]
I don't have much to add here. I guess so long as you've created an android build using this change and run it then I'm happy.

**Pull request merged**
