### PR TITLE
More UNITY_TRANSFER_SHADOW fixes

### PR DESCRIPTION
**Pull request by rblenkinsopp**
## Summary

This fixes the error with `UNITY_TRANSFER_SHADOWS` in some circumstances. It also reformats GenericHandShader.shader as it was a mess.

## Contributor Tasks

- [ ] Pair review with a member of the QA team.
- [ ] Add any release testing considerations to the MR for the next release.
- [x] Check any relevant CHANGELOG files have been updated.
- [x] Ensure documentation requirements are met e.g., public API is commented.
- [x] Consider any licensing/other legal implications for this MR e.g. notices required by any new libraries.
- [x] Add any relevant labels such as `breaking` to this MR.
- [ ] If this MR closes a Jira issue, make sure the fix version on the JIRA issue is set to the correct one.

## Reviewer Tasks

- [ ] Code reviewed.
- [ ] Non-code assets e.g. Unity assets/scenes reviewed.
- [ ] Documentation has been reviewed. Includes checking documentation requirements are met and not missing e.g., public API is commented.
- [ ] Checked and agree with release testing considerations added to MR for the next release.

## Closes JIRA Issue

Closes #UNITY-932

### CODE REVIEW

**Comment by rblenkinsopp** [comment]
Scratch that I found another issue, this isn't quite ready for review.

**Comment by rblenkinsopp** [comment]
@AntonyNasce-UH Has now indicated that this resolves the issue for him, so I think this ready for review @MattGrayUL.

**Comment by MaxPalmer-UH** [comment]
Tested with a mesh that uses the generic hand shader in Windows - e.g. Ghost hands. Build and run with this scene works with no errors.

**Review by MaxPalmer-UH — APPROVED** [review]
Tested this using a mesh that uses the generic hand shader - e.g. set up a scene with the ghost hands prefab. Do a build and run in Windows. Application runs fine.

**Pull request merged**
