### PR TITLE
Move Pinch to Paint to Stable

### PR DESCRIPTION
**Pull request by JuliaRonnebergerUL**
Based on top of PR #1350, and [#1358](https://github.com/ultraleap/UnityPlugin/pull/1358) so those will need to be merged first

## Summary

This moves the pinch to paint example scene from preview into stable.
It also adds an explanation text to the example assets, which has been filled in for each of the XR example scenes and disabled for the non-XR example scenes (as those already had explanations / the size & pos of the XR explanation didn't fit them well)

## Contributor Tasks

_These tasks are for the merge request creator to tick off when creating a merge request._

- [x] Pair review with a member of the QA team.
- [x] Add any release testing considerations to the MR for the next release.
- [x] Check any relevant CHANGELOG files have been updated.
- [x] Ensure documentation requirements are met e.g., public API is commented.
- [x] Consider any licensing/other legal implications for this MR e.g. notices required by any new libraries.
- [x] Add any relevant labels such as `breaking` to this MR.
- [ ] If this MR closes a Jira issue, make sure the fix version on the JIRA issue is set to the correct one.

## Reviewer Tasks

_Add any instructions or tasks for the reviewer such as specific test considerations before this can be merged._

[Use emojis in review threads to communicate intent and help contributors.](https://github.com/ultraleap/UnityPlugin/blob/develop/CONTRIBUTING.md#review-threads)

- [x] Code reviewed.
- [x] Non-code assets e.g. Unity assets/scenes reviewed.
- [x] Documentation has been reviewed. Includes checking documentation requirements are met and not missing e.g., public API is commented.
- [x] Checked and agree with release testing considerations added to MR for the next release.
- [x] Checked & approved the explanation text for every XR example scene

## Closes JIRA Issue

_If this MR closes any JIRA issues list them below in the form `Closes PROJECT-#`_
Closes UNITY-985

### CODE REVIEW

**Comment by JuliaRonnebergerUL** [comment]
Tested:
- There is a paint cursor that is centered at the pinch pos (in the middle of the thumb fingertip and the index findertip)
- The paint cursor consists of two circles and the outer circle adjusts its radius based on the distance between the thumb and index fingertips (smaller distance -> smaller radius)
- When the inner and outer circle overlap, a paint stroke is created which follows the pinch pos
- The paint stroke is finished when the pinch opens enough so that the cursor circles don't overlap anymore
- Even when the hands are a bit shaky (possibly because of tracking) the resulting stroke is relatively smooth

@Greg-UL Can you think of any more tests?

**Comment by Greg-UL** [comment]
It's one of those classic examples where the AC seems to have got lost along the way. 
@JuliaRonnebergerUL can we outline what we want in the scene and what a user should be able to do in the AC on the JIRA ticket please?
At present I definitely wouldn't be able to add much more to the test considerations as there's nothing to go by.

**Comment by JuliaRonnebergerUL** [comment]
@Greg-UL Sorry about that! The ticket that had all the AC on it was this one: https://ultrahaptics.atlassian.net/browse/AUR-47 (which added all the functionality to preview)
I'll copy the AC across to the new ticket and add that this should all be part of stable now :)

**Comment by Greg-UL** [comment]
Cool so we definitely want to test that:
- Audio feedback is engaging/disengaging appropriately.
- Audio feedback is at a suitable volume during changes in drawing speed.
- Paint works with both LeapC and OpenXR

Things i'm interested in
- Can a pinch be achieved with different fingers?
- What happens when we occlude the pinch pose?

**Comment by JuliaRonnebergerUL** [comment]
@Greg-UL 
I have tested everything above and it all works :)

> Can a pinch be achieved with different fingers?

No, it uses the pinch detector which only works for a pinch between the index finger and thumb

> What happens when we occlude the pinch pose?

The stroke stops and a new one starts being drawn as soon as the pinch pose is visible again.
(I also just added an AttachmentHandEnableDisable, so that the paint cursor disappears, in case tracking is lost)

**Review by MattGrayUL — APPROVED** [review]

**Comment by MattGrayUL** [comment]
@Greg-UL I have added a test for this scene under GEU-830

**Pull request merged**
