### PR TITLE
Removed OVRProvider

### PR DESCRIPTION
**Pull request by MattGrayUL**
Removed OVR Provider preview package sample as its functionality is more suitably replaced by OpenXR implementation in the main Package

### CODE REVIEW

**Comment by MaxPalmer-UH** [comment]
Happy with the changes and a quick test. Is this mentioned in our documentation at all (I suspect not).

**Review by MaxPalmer-UH — APPROVED** [review]
Happy with the changes and a quick test (option to import the provider examples has gone).

**Comment by MattGrayUL** [comment]
@MaxPalmer-UH There is no documentation about the OVRProvider on the docs site so I believe this should be sufficient :)

**Review by MaxPalmer-UH — CHANGES_REQUESTED** [review]
Need to fix the packaging issue

**Comment by MattGrayUL** [comment]
@MaxPalmer-UH package issue us fixed now :)

**Comment by MaxPalmer-UH** [comment]
Tbanks

**Review by MaxPalmer-UH — APPROVED** [review]

**Pull request merged**
