### PR TITLE
Normalise position for transform wrist shoulder & don't pass time to …

### PR DESCRIPTION
**Pull request by Dwarph**
## Summary

- Stop passing time to one euro filter and instead rely on the frequency we set it up with (using time can potentially cause some errors)
- Normalize the aim direction calculated in `TransformWristShoulderHandRay`

## Contributor Tasks

- [ ] Create or edit test cases [here](https://ultrahaptics.atlassian.net/projects/UNITY?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/v2/testCases?projectId=15189)
- [ ] Add a CHANGELOG entry for this change.
- [ ] Ensure documentation requirements are met e.g., public API is commented.
- [ ] Consider any licensing/other legal implications for this MR e.g. notices required by any new libraries.
- [ ] Add any relevant labels such as `breaking` to this MR.

## Reviewer Tasks

_Add any instructions or tasks for the reviewer such as specific test considerations before this can be merged._

[Use emojis in review threads to communicate intent and help contributors.](https://github.com/ultraleap/UnityPlugin/blob/develop/CONTRIBUTING.md#review-threads)

- [ ] Run all tests associated with the ticket.
- [x] Code reviewed.
- [x] Non-code assets e.g. Unity assets/scenes reviewed.
- [x] Documentation has been reviewed.
- [x] Approve with a comment of any additional tests run or any observations.

## Closes JIRA Issue

_If this MR closes any JIRA issues list them below in the form `Closes PROJECT-#`_

## Pull Request Templates

Switch template by going to preview and clicking the link - note it will not work if you've made any changes to the description.

- [default.md](?expand=1) - for contributions to stable packages.
- [release.md](?expand=1&template=release.md) - for release merge requests.

**You are currently using: default.md**

Note: these links work by overwriting query parameters of the current url. If the current url contains any you may want to amend the url with `&template=name.md` instead of using the link. See [query parameter docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/using-query-parameters-to-create-a-pull-request) for more information.

### CODE REVIEW

**Comment by MaxPalmer-UH** [comment]
Code changes look fine. @Dwarph you say this is difficult to test/reproduce?

**Comment by Dwarph** [comment]
> Code changes look fine. @Dwarph you say this is difficult to test/reproduce?

yes I'm afraid so - we've done extensive testing trying to reproduce this on a vive focus & pico4 following this change and were unable to, so we're hoping this has fixed the issue 🤞

**Comment by MaxPalmer-UH** [comment]
OK, @Greg-UL, are you happy if I go ahead and merge, sounds like testing is not straightforward?

**Comment by Greg-UL** [comment]
@MaxPalmer-UH @Dwarph 
Does this directly relate to a particular defect?

**Comment by Greg-UL** [comment]
@MaxPalmer-UH I'd probably just retest the telportation scenes in preview? 

There's no potetnial conflict here with our XR and subsytem work is there?

**Comment by Greg-UL** [comment]
Tested telport and rays on Preview just using the Jump Gems and Pinch to Teleport scenes and didn't have any issues. 
Tested using both OpenXR and LeapC.

Looks good to me.

**Review by MaxPalmer-UH — APPROVED** [review]
Happy with these,

**Pull request merged**
