### PR TITLE
Remove FrameTime and HandJointVisualizer from OpenXR

### PR DESCRIPTION
**Pull request by rblenkinsopp**
## Summary

Removes the `FrameTime` enumeration and associated usage, and also removes the `HandJointVisualizer` which has been superseded by the `OpenXRLeapProvider` and Hand visualisers.

## Contributor Tasks

_These tasks are for the merge request creator to tick off when creating a merge request._

- [x] Pair review with a member of the QA team.
- [ ] Add any release testing considerations to the MR for the next release.
- [x] Consider any licensing/other legal implications for this MR e.g. notices required by any new libraries.
- [ ] If this MR closes a Jira issue, make sure the fix version on the JIRA issue is set to the correct one.

## Reviewer Tasks

- [x] Code reviewed.
- [x] Non-code assets e.g. Unity assets/scenes reviewed.
- [ ] Checked and agree with release testing considerations added to MR for the next release.

## Closes JIRA Issue

- Closes [UNITY-869](https://ultrahaptics.atlassian.net/browse/UNITY-869)
- Closes [UNITY-875](https://ultrahaptics.atlassian.net/browse/UNITY-875)

### CODE REVIEW

**Comment by MattGrayUL** [comment]
Holding off on reviewing this until the OpenXR -> Tracking PR is merged 🙂

**Comment by rblenkinsopp** [comment]
This might need an changelog but we may just want to incorporate that into the -> stable note.

**Comment by MattGrayUL** [comment]
> This might need an changelog but we may just want to incorporate that into the -> stable note.

@rblenkinsopp  Yeah I think it is just part of bringing OpenXR into stable at this point? If you feel it necessary, feel free to add a note to the Changes section though :)

**Review by MattGrayUL — APPROVED** [review]

**Comment by MattGrayUL** [comment]
@Greg-UL This PR is removing unnecessary files/code. I have tested this with the same tests I used when bringing OpenXR into stable, everything worked the same (as you'd hope)

I also made a build using android sdk 24 which succeeded, so I believe all necessary coverage has been done :)

Would you like to run any other tests here?

**Comment by Greg-UL** [comment]
I'd be interested in knowing how fast and slow hand motion through FoV was tracking as well as losing and regaining tracking. 
From a regression PoV does the removal of the HandJointVisualizer impact on our existing assets or service providers?

**Comment by MattGrayUL** [comment]
@Greg-UL  I tested the speeds in editor, felt the same here as it did in the previous PR

In terms of regressions, it is all separate from existing tests as this is OpenXR content only, so does not impact them. The only change I guess is that we need to make sure the OpenXR example scene is tested upon releases (i believe we mentioned that in the previous PR but we should make sure 🙂)

**Comment by Greg-UL** [comment]
All good from my perspective, thanks Matt.

**Pull request merged**
