### PR TITLE
make pinch to paint example allow audio when the pinch begins outside of tracking

### PR DESCRIPTION
**Pull request by MattGrayUL**
## Summary

make pinch to paint example allow audio when the pinch begins outside of tracking range

## Contributor Tasks

- [x] Create or edit test cases [here](https://ultrahaptics.atlassian.net/projects/UNITY?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/v2/testCases?projectId=15189)
- [x] Add a CHANGELOG entry for this change.
- [x] Ensure documentation requirements are met e.g., public API is commented.
- [x] Consider any licensing/other legal implications for this MR e.g. notices required by any new libraries.

## Test Cycle

[Test Cycle here](https://ultrahaptics.atlassian.net/projects/UNITY?selectedItem=com.atlassian.plugins.atlassian-connect-plugin:com.kanoah.test-manager__main-project-page#!/testPlayer/UNITY-R83)

## Reviewer Tasks

- [x] Code reviewed.
- [x] Non-code assets e.g. Unity assets/scenes reviewed.
- [x] All tests must be ran and cover all scenarios (If not, add new tests to the cycle and run them).
- [x] Documentation has been reviewed.
- [x] Approve with a comment of any additional tests run or any observations.

## Related JIRA Issues

Closes [UNITY-998](https://ultrahaptics.atlassian.net/browse/UNITY-998)

[UNITY-998]: https://ultrahaptics.atlassian.net/browse/UNITY-998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by MaxPalmer-UH** [comment]
I'm not convinced these changes fix the issue. Also, they weren't pulled when I pulled the branch, manually adding them didn't fix the issue.

**Comment by MattGrayUL** [comment]
> I'm not convinced these changes fix the issue. Also, they weren't pulled when I pulled the branch, manually adding them didn't fix the issue.

@MaxPalmer-UH can I check that you also imported the example scenes again after pulling this branch? The change includes a scene change which won't be included without re-importing the examples

**Comment by MaxPalmer-UH** [comment]
> > I'm not convinced these changes fix the issue. Also, they weren't pulled when I pulled the branch, manually adding them didn't fix the issue.
> 
> @MaxPalmer-UH can I check that you also imported the example scenes again after pulling this branch? The change includes a scene change which won't be included without re-importing the examples

I reimported in the examples - BUT - I  didn't see changes on this branch so something odd was going on - I bet the example scene didn't change.

**Review by BryceNewell-UL — APPROVED** [review]
Scene works well once reimported

**Pull request merged**
